cask 'google-chrome'
cask 'cleanmymac'
cask 'dropbox'
cask 'flux'
cask 'gpgtools'
cask 'imagealpha'
cask 'imageoptim'
cask 'iterm2'
cask 'keepingyouawake'
cask 'launchrocket'
cask 'qlmarkdown'
cask 'selfcontrol'
cask 'slack'
cask 'slate'
cask 'spotify'
cask 'the-unarchiver'
cask 'vlc'
cask 'xquartz'
cask 'nylas-n1'

brew 'openssl'
brew 'curl'
brew 'git'
brew 'ruby-build'
brew 'rbenv'
brew 'redis'
brew 'hub'

