cask 'flux'
cask 'gpgtools'
cask 'imagealpha'
cask 'imageoptim'
cask 'keepingyouawake'
cask 'private-internet-access'
cask 'slate'
cask 'the-unarchiver'
cask 'vlc'
cask 'xquartz'

brew 'curl'
brew 'hub'
